/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_demo_jni_Register */

#ifndef _Included_com_demo_jni_Register
#define _Included_com_demo_jni_Register
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_jni_Register
 * Method:    HelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_demo_jni_Register_HelloWorld
  (JNIEnv *, jobject);
JNIEXPORT jstring JNICALL Java_com_demo_jni_Register_sayHello
        (JNIEnv *, jclass ,jstring);
JNIEXPORT jstring JNICALL Java_com_demo_jni_Register_sayChineseHello
        (JNIEnv *, jclass ,jstring);
JNIEXPORT jstring JNICALL Java_com_demo_jni_Register_testFeild
        (JNIEnv *, jobject);
JNIEXPORT jstring JNICALL Java_com_demo_jni_Register_testStaticField
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_demo_jni_Register_callJavaConstructMethod
        (JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_com_demo_jni_Register_callJavaMethod
        (JNIEnv *, jobject);
JNIEXPORT jobject JNICALL Java_com_demo_jni_Register_callJavaObjectMethod
        (JNIEnv *, jobject);




#ifdef __cplusplus
}
#endif
#endif
