/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class demo_Register */

#ifndef _Included_demo_Register
#define _Included_demo_Register
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_Register
 * Method:    HelloWord
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_demo_Register_HelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
